### PR TITLE
Workaround for Intel compiler issue mentioned in #215

### LINKED ISSUE #215: Elemental 0.87 release Intel 17.0.1 compilation error
A fresh build of Elemental 0.87 (01/05/2017) failed to compile in Intel 17.0.1 due to incompatible declarations in DistMatrix, however the compilation went flawless in GCC 5.3.0.

`[13%]Building CXX object CMakeFiles/El.dir/src/core/DistMatrix/Block/CIRC_CIRC.cpp.o`
In file included from `/home/mselvam/Elemental/version_source2/Elemental/src/core/DistMatrix/Block/CIRC_CIRC.cpp(15):`
`/home/mselvam/Elemental/version_source2/Elemental/src/core/DistMatrix/Block/./setup.hpp(168): error:` `declaration is incompatible with "El::DistMatrix<Ring, El::DistNS::CIRC, El::DistNS::CIRC,` `El::DistWrapNS::BLOCK>::diagType *El::DistMatrix<Ring, El::DistNS::CIRC, El::DistNS::CIRC,` `El::DistWrapNS::BLOCK>::ConstructDiagonal(const El::Grid &, int) const" (declared at line 68 of` `"/home/mselvam/Elemental/version_source2/Elemental/include/El/core/DistMatrix/Block/CIRC_CIRC.hpp")`
  `BDM::ConstructDiagonal`
       ^
 
`compilation aborted for` `/home/mselvam/Elemental/version_source2/Elemental/src/core/DistMatrix/Block/CIRC_CIRC.cpp (code 2)`
`make[2]: *** [CMakeFiles/El.dir/src/core/DistMatrix/Block/CIRC_CIRC.cpp.o] Error 2`

### PR DESCRIPTION
**Pull request by trb413**
Fixes #215 for Intel 17+. I tested with 16.0.3, 17.0.0, 17.0.2, and 18.0-beta, and life's (mostly) good. With 16.0.3 and 17.0.0, I ran into some other issues (see #177) so the compilation doesn't finish -- BUT! It gets past the matrix classes, which is the problem in #215 . 17.0.2 and 18.0-beta compiled just fine and the tests passed for me. Likewise, compiling with GCC 6.1.0 and 7.1.0 is still good.

### CODE REVIEW

**Comment by jeffhammond** [comment]
I will test this extensively and then merge.

**Comment by trb413** [comment]
Thanks. Admittedly, I just tested the Elemental configuration that I happen to use anyway on the suite of compilers I had in front of me, so it definitely isn't rigorous across configuration options or compiler versions. Hopefully the fix works. Meanwhile, I'm trying to come up with a MWE that illustrates this bug without all the preprocessor indirection (misdirection?) in Elemental. Hopefully that will be helpful to someone.

**Comment by jeffhammond** [comment]
I'm not seeing any issues here.

**Comment by jeffhammond** [comment]
I tested Intel 18.0.1,  GCC 5.4.1, and Clang 4.0.0, which together with Travis covers everything we care about.  Elemental deprecated support for IBM compilers years ago and has never attempted any other toolchains (e.g. PGI and Cray, although I added CMake support for CCE a while back).

I think it's perfectly reasonable to require the use of Intel 17.0.2 or later.

**Comment by jeffhammond** [comment]
And thanks to both @trb413 and @benson31 for fixing this!  It's pretty sad that so much effort went into dealing with something that had such a simple solution.  I wish I understood C++ well enough to fix stuff like this.
